### ISSUE TITLE
Update to v45

### ISSUE THREAD

**Issue by Higgins4k** [ege-adam/MoreScreams#4]
Does there need to be a update for v45? All my other mods have updated for the game update

**Comment by ege-adam** [comment]
Code is unchanged, since the modified parts of the game unchanged with v45. The older version must be working fine, however I've uploaded a new build; a build with libraries from v45. I will close the issue now. Feel free to reopen if you face a problem.

[1.0.3](https://github.com/ege-adam/MoreScreams/releases/tag/1.0.3)
